# Generated by Django 5.1 on 2024-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=20)),
                ('Telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('id_sucursal', models.CharField(max_length=20)),
            ],
        ),
    ]
