# Generated by Django 5.1.2 on 2024-12-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('num_empleados', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('productos', models.CharField(max_length=200)),
                ('numero_productos', models.IntegerField()),
                ('Telefono', models.IntegerField()),
            ],
        ),
    ]
