# Generated by Django 5.1.2 on 2024-12-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id_distribuidor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('productos', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('nie', models.IntegerField()),
                ('cant_producto', models.DateField()),
            ],
        ),
    ]
