# Generated by Django 5.1.2 on 2024-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='cant_producto',
            field=models.IntegerField(),
        ),
    ]
